meta_product_name: "BiciCouriers"
meta_title: "BiciCouriers - Livraison à vélo sur Nantes"
meta_description: "Nous somme spécialiste de la livraisons express sur Nantes, nous livrons pour vous professionnel ou particulier plis et colis dans nos offres sur mesures"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@BiciNantes"   # required for Twitter Cards
